version: '2'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wildlife_sites_root
      MYSQL_USER: wildlife_user
      MYSQL_PASSWORD: wildlife_sites_password
      MYSQL_DATABASE: wildlife_sites_db
    volumes:
      - wildlife_sites_var_lib_mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

volumes:
  wildlife_sites_var_lib_mysql: {}
