# Generated by Django 2.2.2 on 2019-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=1024)),
                ('common_name_english', models.CharField(max_length=1024)),
                ('common_name_catalan', models.CharField(max_length=1024)),
                ('common_name_spanish', models.CharField(max_length=1024)),
            ],
        ),
    ]
