# Generated by Django 2.2.2 on 2019-07-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevisit',
            old_name='timeofyear',
            new_name='time_of_year',
        ),
    ]
