# Generated by Django 2.2.2 on 2019-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sites', '0002_auto_20190707_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyclass',
            name='class',
            field=models.CharField(default='Aves', max_length=256),
            preserve_default=False,
        ),
    ]
