# Generated by Django 2.2.2 on 2019-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sites', '0002_auto_20190706_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='time_of_year',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='time_of_year',
            field=models.ManyToManyField(blank=True, to='wildlife_sites.TimeOfYear'),
        ),
    ]
