# Generated by Django 2.2.2 on 2019-07-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sites', '0004_auto_20190707_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wildlife_sites.TaxonomyOrder'),
        ),
    ]
