# Generated by Django 2.2.2 on 2020-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_sites', '0005_auto_20190707_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyclass',
            name='taxclass',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomyorder',
            name='order',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
